Repository APP-iOS3rd/PJ4T5_TrackUs, pull requests merged in 2024-02, with the labels that each got.

#19 #14, #15 Feat: 로그인, 회원가입 추가보기
  TrackUs/TrackUs.xcodeproj/project.pbxproj
  TrackUs/TrackUs/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/AppIcon.appiconset/appstore.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/FemaleGray1.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/FemaleGray1.imageset/FemaleGray1.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/FemaleLogo.imageset/FemaleLogo.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/FemaleMain.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/FemaleMain.imageset/FemaleMain.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/GoogleLogo.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/GoogleLogo.imageset/GoogleLogo.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/LoginImage.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/LoginImage.imageset/LoginImage.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/MaleGray1.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/MaleGray1.imageset/MaleGray1.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/MaleLogo.imageset/MaleLogo.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/MaleMain.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/MaleMain.imageset/MaleMain.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/TrackUsLogo.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/TrackUsLogo.imageset/TrackUsLogo.png
  TrackUs/TrackUs/Resources/Fonts/Roboto-Medium.ttf
  TrackUs/TrackUs/Sources/Authentication/View/AgeGenderView.swift
  TrackUs/TrackUs/Sources/Authentication/View/DailyGoalView.swift
  TrackUs/TrackUs/Sources/Authentication/View/Description.swift
  TrackUs/TrackUs/Sources/Authentication/View/LoginView.swift
  TrackUs/TrackUs/Sources/Authentication/View/NickNameView.swift
  TrackUs/TrackUs/Sources/Authentication/View/PhysicalView.swift
  TrackUs/TrackUs/Sources/Authentication/View/ProfileImageView.swift
  TrackUs/TrackUs/Sources/Authentication/View/RunningStyleView.swift
  TrackUs/TrackUs/Sources/Authentication/View/SignUpView.swift
  TrackUs/TrackUs/Sources/Commons/Extensions/Font+.swift
  TrackUs/TrackUs/Sources/Commons/Items/MainButton.swift
  TrackUs/TrackUs/Sources/Commons/Items/NickNameTextFiled.swift
  TrackUs/TrackUs/Sources/Commons/Items/ProfilePicker.swift
  TrackUs/TrackUs/Sources/Commons/Items/SelectButton.swift
  TrackUs/TrackUs/Sources/Commons/Items/SelectPicker.swift
  TrackUs/TrackUs/Sources/Root/MainTabView.swift
Labels: 🍎 기능구현, 🏃🏻 로그인뷰

#23 #23 fix: MainTabView 수정
  TrackUs/TrackUs.xcodeproj/project.pbxproj
  TrackUs/TrackUs/Resources/Assets.xcassets/Chatting.imageset/Chatting.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Chatting.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Chatting.fill.imageset/Chatting.fill.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Chatting.fill.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Profile.fill.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Profile.fill.imageset/Profile.fill.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Profile.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Profile.imageset/Profile.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Recruitment.fill.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Recruitment.fill.imageset/Recruitment.fill.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Recruitment.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Recruitment.imageset/Recruitment.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Report.fill.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Report.fill.imageset/Report.fill.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Report.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Report.imageset/Report.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Running.fill.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Running.fill.imageset/Running.fill.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Running.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Running.imageset/Running.png
  TrackUs/TrackUs/Sources/Chatting/View/ChattingView.swift
  TrackUs/TrackUs/Sources/Chatting/ViewModel/ChattingViewModel.swift
  TrackUs/TrackUs/Sources/Commons/Extensions/Font+.swift
  TrackUs/TrackUs/Sources/Recruitment/View/RecruitmentView.swift
  TrackUs/TrackUs/Sources/Recruitment/ViewModel/RecruitmentViewModel.swift
  TrackUs/TrackUs/Sources/Root/MainTabView.swift
Labels: 🎨 디자인변경

#25 [#21, #24] feat: Keyboardhide extension, WebView 로딩 인디케이터
  TrackUs/TrackUs.xcodeproj/project.pbxproj
  TrackUs/TrackUs/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  TrackUs/TrackUs/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/AppIcon.appiconset/appstore.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Chatting.imageset/Chatting.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Chatting.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Chatting.fill.imageset/Chatting.fill.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Chatting.imageset/Chatting.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Chatting.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Profile.fill.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Profile.fill.imageset/Profile.fill.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Profile.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Profile.imageset/Profile.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Recruitment.fill.imageset/Recruitment.fill.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Recruitment.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Recruitment.imageset/Recruitment.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Report.fill.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Report.fill.imageset/Report.fill.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Report.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Report.imageset/Report 1.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Report.imageset/Report.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Running.fill.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Running.fill.imageset/Running.fill.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Running.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Running.imageset/Running.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Star.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Star.imageset/Star.png
  TrackUs/TrackUs/Sources/Commons/Extensions/View+Keyboard.swift
  TrackUs/TrackUs/Sources/Commons/Items/MenuItems.swift
  TrackUs/TrackUs/Sources/Commons/ViewModel/Router.swift
  TrackUs/TrackUs/Sources/MyProfile/View/MyProfileView.swift
  TrackUs/TrackUs/Sources/MyProfile/View/PremiumPaymentView.swift
  TrackUs/TrackUs/Sources/MyProfile/View/ProfileEditView.swift
  TrackUs/TrackUs/Sources/MyProfile/View/SettingsView.swift
  TrackUs/TrackUs/Sources/MyProfile/View/WebView.swift
  TrackUs/TrackUs/Sources/Root/MainTabView.swift
Labels: 🍎 기능구현, 🏃🏻 마이페이지뷰

#30 #29 fix: 마이프로필 화면이동시 갇히는 오류 해결
  TrackUs/TrackUs/Sources/MyProfile/View/ProfileEditView.swift
  TrackUs/TrackUs/Sources/Root/TrackUsApp.swift
Labels: 🚨 버그

#34 [#31, #33, #36] TabBar 터치시 Haptic Feedback 추가, 화면이동 오류 수정
  TrackUs/TrackUs.xcodeproj/project.pbxproj
  TrackUs/TrackUs/Sources/Commons/Extensions/UINavigationController+.swift
  TrackUs/TrackUs/Sources/Commons/HapticManager.swift
  TrackUs/TrackUs/Sources/MyProfile/View/ExerciseView.swift
  TrackUs/TrackUs/Sources/MyProfile/View/ProfileEditView.swift
  TrackUs/TrackUs/Sources/Root/MainTabView.swift
  TrackUs/com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist.latest_result.txt
  TrackUs/com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist.plist
  TrackUs/com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/GoogleAppMeasurement.plist
  TrackUs/com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/GoogleDataTransport.plist
  TrackUs/com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/GoogleUtilities.plist
  TrackUs/com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/abseil-cpp-binary.plist
  TrackUs/com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/app-check.plist
  TrackUs/com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/firebase-ios-sdk.plist
  TrackUs/com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/grpc-binary.plist
  TrackUs/com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/gtm-session-fetcher.plist
  TrackUs/com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/interop-ios-for-google-sdks.plist
  TrackUs/com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/leveldb.plist
  TrackUs/com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/mapbox-common-ios.plist
  TrackUs/com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/mapbox-maps-ios.plist
  TrackUs/com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/nanopb.plist
  TrackUs/com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/promises.plist
  TrackUs/com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/swift-protobuf.plist
  TrackUs/com.mono0926.LicensePlist.Output/com.mono0926.LicensePlist/turf-swift.plist
Labels: 🍎 기능구현, 🚨 버그

#38 #1 RunningView 화면 구현
  TrackUs/TrackUs.xcodeproj/project.pbxproj
  TrackUs/TrackUs.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TrackUs/TrackUs/Resources/Assets.xcassets/Color/Indicator.colorset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/BigFire.imageset/BigFire.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/BigFire.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Clipboard.imageset/Clipboard.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Clipboard.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Fire.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Fire.imageset/Fire.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/MapPath.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/MapPath.imageset/MapPath.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Power.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Power.imageset/Power.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Setting.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Setting.imageset/Setting.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Shose.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Shose.imageset/Shose.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/SmallFire.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/SmallFire.imageset/SmallFire.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Time.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Time.imageset/Time.png
  TrackUs/TrackUs/Sources/Chatting/View/ChattingView.swift
  TrackUs/TrackUs/Sources/Commons/Constants.swift
  TrackUs/TrackUs/Sources/Commons/Extensions/Color+.swift
  TrackUs/TrackUs/Sources/Commons/Extensions/Font+.swift
  TrackUs/TrackUs/Sources/Commons/Items/BottomSheet.swift
  TrackUs/TrackUs/Sources/Commons/Items/MaxBoxMapView.swift
  TrackUs/TrackUs/Sources/Commons/Items/PreparingService.swift
  TrackUs/TrackUs/Sources/Commons/LocationManager.swift
  TrackUs/TrackUs/Sources/MyProfile/View/MyProfileView.swift
  TrackUs/TrackUs/Sources/MyProfile/View/PremiumPaymentView.swift
  TrackUs/TrackUs/Sources/MyProfile/View/RunningRecordView.swift
  TrackUs/TrackUs/Sources/MyProfile/View/SettingsView.swift
  TrackUs/TrackUs/Sources/Recruitment/View/RecruitmentView.swift
  TrackUs/TrackUs/Sources/Report/View/ReportView.swift
  TrackUs/TrackUs/Sources/Root/MainTabView.swift
  TrackUs/TrackUs/Sources/Running/View/NavigationLinkCard.swift
  TrackUs/TrackUs/Sources/Running/View/RunningHomeView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningLiveView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningRecruitmentCell.swift
  TrackUs/TrackUs/Sources/Running/View/RunningResultView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningView.swift
  TrackUs/TrackUs/Sources/Running/View/SettingPopup.swift
  TrackUs/TrackUs/Sources/Running/ViewModel/CountViewModel.swift
Labels: 🏃🏻 러닝뷰, 🎨 디자인변경

#44 [#37, #43] RunningView 오류 수정, 맵뷰 일부 수정
  TrackUs/TrackUs.xcodeproj/project.pbxproj
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Pace.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Pace.imageset/Pace.png
  TrackUs/TrackUs/Sources/Commons/Extensions/UINavigationController+.swift
  TrackUs/TrackUs/Sources/Commons/Extensions/View+Gesture.swift
  TrackUs/TrackUs/Sources/Commons/Items/BottomSheet.swift
  TrackUs/TrackUs/Sources/Commons/Items/MaxBoxMapView.swift
  TrackUs/TrackUs/Sources/Commons/Modifiers/PreventionGestureModifier.swift
  TrackUs/TrackUs/Sources/Commons/ViewModel/Router.swift
  TrackUs/TrackUs/Sources/MyProfile/View/MyProfileView.swift
  TrackUs/TrackUs/Sources/MyProfile/View/PremiumPaymentView.swift
  TrackUs/TrackUs/Sources/MyProfile/View/SettingsView.swift
  TrackUs/TrackUs/Sources/Root/MainTabView.swift
  TrackUs/TrackUs/Sources/Running/View/NavigationLinkCard.swift
  TrackUs/TrackUs/Sources/Running/View/RunningHomeView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningLiveView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningResultView.swift
  TrackUs/TrackUs/Sources/Running/View/SettingPopup.swift
Labels: 🏃🏻 러닝뷰, 🚨 버그

#46 #46 RunningView 현위치로 이동하는 LocationButton 구현
  TrackUs/TrackUs.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/locationButton.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/locationButton.imageset/locationButton.png
  TrackUs/TrackUs/Sources/Commons/Items/MaxBoxMapView.swift
Labels: 🍎 기능구현, 🏃🏻 러닝뷰

#47 [#42] MyProfieView 회원정보 불러오기, 회원탈퇴 기능구현
  TrackUs/TrackUs.xcodeproj/project.pbxproj
  TrackUs/TrackUs/Sources/Authentication/ViewModel/UserInfoViewModel.swift
  TrackUs/TrackUs/Sources/MyProfile/View/MyProfileView.swift
  TrackUs/TrackUs/Sources/MyProfile/View/ProfileEditView.swift
  TrackUs/TrackUs/Sources/MyProfile/View/Withdrawal.swift
Labels: 🍎 기능구현, 🏃🏻 마이페이지뷰

#54 Feature/running view
  TrackUs/TrackUs.xcodeproj/project.pbxproj
  TrackUs/TrackUs.xcodeproj/xcshareddata/xcschemes/TrackUs.xcscheme
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Puck.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Puck.imageset/Puck.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/StartPin.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/StartPin.imageset/StartPin.png
  TrackUs/TrackUs/Sources/Commons/API/ImageUploader.swift
  TrackUs/TrackUs/Sources/Commons/Constants.swift
  TrackUs/TrackUs/Sources/Commons/Extensions/Double+.swift
  TrackUs/TrackUs/Sources/Commons/LocationManager.swift
  TrackUs/TrackUs/Sources/Commons/Model/RunningData.swift
  TrackUs/TrackUs/Sources/Commons/ViewModel/Router.swift
  TrackUs/TrackUs/Sources/MyProfile/View/Withdrawal.swift
  TrackUs/TrackUs/Sources/Running/View/MapViewRepresentable.swift
  TrackUs/TrackUs/Sources/Running/View/RunningHomeView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningLiveView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningResultView.swift
  TrackUs/TrackUs/Sources/Running/ViewModel/MapViewModel.swift
Labels: 🍎 기능구현, 🏃🏻 러닝뷰

#61 [#53, #58] 메인화면 프로필사진 무한로딩 오류, 결과화면 텍스트 잘림현상
  .github/ISSUE_TEMPLATE/pull_request_template.md
  .github/ISSUE_TEMPLATE/🐞-bug.md
  .github/ISSUE_TEMPLATE/🛠️-feature.md
  .github/pull_request_template.md
  README.md
  TrackUs/TrackUs.xcodeproj/project.pbxproj
  TrackUs/TrackUs.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TrackUs/TrackUs/Sources/Authentication/ViewModel/AuthenticationViewModel.swift
  TrackUs/TrackUs/Sources/Commons/Items/GraphicTextCard.swift
  TrackUs/TrackUs/Sources/Commons/Items/MaxBoxMapView.swift
  TrackUs/TrackUs/Sources/Commons/Model/RunningRecord.swift
  TrackUs/TrackUs/Sources/Commons/Modifiers/BorderLineModifier.swift
  TrackUs/TrackUs/Sources/Commons/ViewModel/Router.swift
  TrackUs/TrackUs/Sources/Report/View/MyReportView.swift
  TrackUs/TrackUs/Sources/Running/View/MapViewRepresentable.swift
  TrackUs/TrackUs/Sources/Running/View/RunningHomeView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningLiveView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningResultView.swift
  TrackUs/TrackUs/Sources/Running/ViewModel/MapViewModel.swift
Labels: 🚨 버그

#65 [#65] Feature/running view
  TrackUs/TrackUs.xcodeproj/project.pbxproj
  TrackUs/TrackUs.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TrackUs/TrackUs/Sources/MyProfile/View/ProfileEditView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningHomeView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningLiveView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningResultView.swift
  TrackUs/TrackUs/Sources/Running/View/SettingPopup.swift
  TrackUs/TrackUs/Sources/Running/ViewModel/MapViewModel.swift
  TrackUs/TrackUs/Sources/Running/ViewModel/SettingPopupViewModel.swift
Labels: 🍎 기능구현, 🏃🏻 러닝뷰

#69 [#67] 러닝결과화면 수정된 디자인으로 변경, 한글주소 저장되도록 수정(DB)
  .github/ISSUE_TEMPLATE/🏃🏻-feature.md
  .github/ISSUE_TEMPLATE/🛠️-refactor.md
  TrackUs/TrackUs.xcodeproj/project.pbxproj
  TrackUs/TrackUs.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TrackUs/TrackUs/Sources/Commons/Items/MainButton.swift
  TrackUs/TrackUs/Sources/Commons/LocationManager.swift
  TrackUs/TrackUs/Sources/Commons/ViewModel/Router.swift
  TrackUs/TrackUs/Sources/Running/View/MapViewRepresentable.swift
  TrackUs/TrackUs/Sources/Running/View/RunningLiveView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningResultView.swift
  TrackUs/TrackUs/Sources/Running/ViewModel/MapViewModel.swift
Labels: 🍎 기능구현, 🏃🏻 러닝뷰, 🎨 디자인변경

#73 [#64] 라이브트래킹 코드 리펙토링
  TrackUs/TrackUs.xcodeproj/project.pbxproj
  TrackUs/TrackUs.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TrackUs/TrackUs/Sources/Commons/Extensions/Color+.swift
  TrackUs/TrackUs/Sources/Commons/Extensions/Double+.swift
  TrackUs/TrackUs/Sources/Commons/Extensions/UIImage+.swift
  TrackUs/TrackUs/Sources/Commons/Extensions/View+.swift
  TrackUs/TrackUs/Sources/Commons/Items/MaxBoxMapView.swift
  TrackUs/TrackUs/Sources/Commons/LocationManager.swift
  TrackUs/TrackUs/Sources/Commons/Modifiers/CustomNavigationBarModifier.swift
  TrackUs/TrackUs/Sources/Commons/Modifiers/LoadingModifier.swift
  TrackUs/TrackUs/Sources/Commons/ViewModel/Router.swift
  TrackUs/TrackUs/Sources/Report/View/MyRecordDetailView.swift
  TrackUs/TrackUs/Sources/Running/Item/MapViewRepresentable.swift
  TrackUs/TrackUs/Sources/Running/Item/RunningRecruitmentCell.swift
  TrackUs/TrackUs/Sources/Running/Item/SaveDataPopup.swift
  TrackUs/TrackUs/Sources/Running/Item/SettingPopup.swift
  TrackUs/TrackUs/Sources/Running/View/DataLoadingView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningHomeView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningLiveView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningResultView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningStartView.swift
  TrackUs/TrackUs/Sources/Running/View/TrackingModeMapView.swift
  TrackUs/TrackUs/Sources/Running/ViewModel/CountViewModel.swift
  TrackUs/TrackUs/Sources/Running/ViewModel/ExerciseManager.swift
  TrackUs/TrackUs/Sources/Running/ViewModel/MapViewModel.swift
  TrackUs/TrackUs/Sources/Running/ViewModel/RunningViewModel.swift
  TrackUs/TrackUs/Sources/Running/ViewModel/SettingPopupViewModel.swift
  TrackUs/TrackUs/Sources/Running/ViewModel/TrackingViewModel.swift
Labels: 🛠️ 리펙토링, 🏃🏻 러닝뷰, 🚨 버그

#80 [#77] 리포트 오류 수정
  TrackUs/TrackUs.xcodeproj/project.pbxproj
  TrackUs/TrackUs.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TrackUs/TrackUs/Sources/Report/View/AgeGraphView.swift
  TrackUs/TrackUs/Sources/Report/View/BarGraphView.swift
  TrackUs/TrackUs/Sources/Report/View/CircleTabView.swift
  TrackUs/TrackUs/Sources/Report/View/HorizontalGraph.swift
  TrackUs/TrackUs/Sources/Report/View/MyRecordDetailView.swift
  TrackUs/TrackUs/Sources/Report/View/MyRecordView.swift
  TrackUs/TrackUs/Sources/Report/View/ReportView.swift
  TrackUs/TrackUs/Sources/Report/ViewModel/RecordViewModel.swift
  TrackUs/TrackUs/Sources/Report/ViewModel/ReportViewModel.swift
  TrackUs/TrackUs/Sources/UserProfile/View/UserProfileView.swift
Labels: 🛠️ 리펙토링, 🏃🏻 리포트뷰, 🚨 버그

#83 feat: 러닝코스 등록하도록 수정(추가작업 예정) (#74)
  TrackUs/TrackUs.xcodeproj/project.pbxproj
  TrackUs/TrackUs/Sources/Commons/Constants.swift
  TrackUs/TrackUs/Sources/Commons/Extensions/Array+CLLocationCoordinate2D.swift
  TrackUs/TrackUs/Sources/Commons/Items/RunningStyleBadge.swift
  TrackUs/TrackUs/Sources/Commons/Model/Course.swift
  TrackUs/TrackUs/Sources/Commons/ViewModel/Router.swift
  TrackUs/TrackUs/Sources/Running/Item/RunningRecruitmentCell.swift
  TrackUs/TrackUs/Sources/Running/View/CourseDetailView.swift
  TrackUs/TrackUs/Sources/Running/View/CourseRegisterView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningHomeView.swift
  TrackUs/TrackUs/Sources/Running/ViewModel/CourseRegViewModel.swift
  TrackUs/TrackUs/Sources/Running/ViewModel/CourseViewModel.swift
Labels: 🍎 기능구현

#102 fix: 러닝기록 상세보기에서 예상 데이터들을 제대로 표시하게끔 수정
  TrackUs/TrackUs/Sources/Report/View/MyRecordDetailView.swift
  TrackUs/TrackUs/Sources/Report/ViewModel/ReportViewModel.swift
  TrackUs/TrackUs/Sources/UserProfile/ViewModle/UserProfileViewModel.swift
Labels: 🚨 버그

#104 [#104] 러닝 모집 버튼 및 필터 버튼 추가
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Filter.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Filter.imageset/Filter.png
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Plus.imageset/Contents.json
  TrackUs/TrackUs/Resources/Assets.xcassets/Image/Plus.imageset/Plus.png
  TrackUs/TrackUs/Sources/Commons/MapViews/LocationMeMapView.swift
Labels: 🎨 디자인변경

#106 변경된 맵뷰에 버튼동작 연결
  TrackUs/TrackUs/Sources/Commons/ViewModel/Router.swift
  TrackUs/TrackUs/Sources/Running/View/CourseRegisterView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningHomeView.swift
  TrackUs/TrackUs/Sources/Running/View/RunningSelectView.swift
  TrackUs/TrackUs/Sources/Running/ViewModel/CourseRegViewModel.swift
Labels: 🍎 기능구현, 🏃🏻 러닝뷰, 🎨 디자인변경

#108 fix: 메인화면 진입시 사용자 uid가 없는경우 대체뷰 나타나도록 수정
  TrackUs/TrackUs/Sources/Running/View/RunningHomeView.swift
Labels: 🚨 버그
